US/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^tipo/(?P<pk>[0-9]+)/$', detail_tipo_us, name='tipo_us_detail'),
    url(r'^tipo/$', list_tipo_us),
    url(r'^tipo/create/$',create_tipo),
    url(r'^tipo/delete/(?P<pk>[0-9]+)/$', delete_tipo_us, name='tipo_us_delete'),
    url(r'^tipo/update/(?P<pk>[0-9]+)/$', update_tipo_us, name='tipo_us_update'),
    url(r'^actividades/create/(?P<pk>[0-9]+)/$', create_actividad, name='actividad_create'),
    url(r'^actividades/(?P<pk>[0-9]+)/$', list_actividades, name='actividad_list'),
    url(r'^actividades/delete/(?P<pk>[0-9]+)/$', delete_actividad, name='actividad_delete'),
    url(r'^us/create/(?P<pk>[0-9]+)/$', create_us, name='us_create'),
    url(r'^us/delete/(?P<pk>[0-9]+)/$', delete_us, name='us_delete'),
    url(r'^us/update/(?P<pk>[0-9]+)/$', update_us, name='us_update'),
    url(r'^us/(?P<pk>[0-9]+)/$', detail_us, name='us_detail'),
    url(r'^us/cambiar_actividad/(?P<pk>[0-9]+)/$', cambiar_actividad, name='cambiar_actividad'),
    url(r'^us/cambiar_estado_actividad/(?P<pk>[0-9]+)/$', cambiar_estado_actividad, name='cambiar_estado_actividad'),
    url(r'^us/repriorizar/(?P<pk>[0-9]+)/$', repriorizar, name='repriorizar')

]

sistema_proyectos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'',include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^proyecto/', include('proyecto.urls')),
    url(r'^cliente/', include ('cliente.urls')),
    url(r'^equipo/', include('equipo.urls')),
    url(r'^sprint/', include('sprint.urls')),
    url(r'^us/', include ('US.urls')),
]

US/models.py
from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.db import models
from proyecto.models import Proyecto
from sprint.models import Sprint
from login.models import Usuario

# Create your models here.


class TipoUS(models.Model):
    """
    Clase TipoUS que hereda de models.Model
    nombre = El nombre del tipo de US
    """
    nombre = models.TextField(default="")

    history = AuditlogHistoryField()
    class Meta:
        permissions = (
            ("ver_tipo_US", "Puede ver tipos de US"),
        )

    def __unicode__(self):
        return self.nombre



class Actividades(models.Model):
    """
    Clase Actividades que hereda de models.Model
    nombre = Nombre de la actividad
    tipoUS= Tipo dee US al que pertenece la actividad.
    """

    nombre = models.TextField(default="")
    tipoUS = models.ForeignKey(TipoUS, related_name='actividades')
    numero = models.IntegerField(default=0)

    history = AuditlogHistoryField()

    class Meta:
        permissions = (
            ("ver_actividades", "Puede ver actividades"),
            ("crear_actividades", "Puede crear actividades"),
        )

    def __unicode__(self):
        return self.nombre

class US(models.Model):
    """
    Clase US que hereda de models.Model.
    sprint = Sprint al que esta asignado el US.
    proyecto = Proyecto al que pertenece el US.
    descripcion_corta = Descripcion corta del US.
    descripcion_larga = Descripcion larga del US.
    tiempo_planificado = Tiempo aproximado que tomaria terminar el US.
    valor_negocio = Entero que representa el valor del US en el proyecto.
    urgencia = Entero que representa la urgencia para terminar el US.
    tipoUS = Tipo de US del US, define el flujo a utilizar.
    actividad = Actividad actual del US dentro del flujo.
    estado_actividad = Estado de la actividad actual.
    """
    sprint = models.ForeignKey(Sprint, null=True,blank=True, related_name='uss')
    proyecto = models.ForeignKey(Proyecto,null=True,related_name='uss')
    descripcion_corta = models.TextField(default="")
    descripcion_larga = models.TextField(default="")
    tiempo_planificado = models.IntegerField(default=0)
    valor_negocio = models.IntegerField(default=1)  # 0 a 4
    urgencia = models.IntegerField(default=1)  # 0 a 4
    usuario_asignado = models.ForeignKey(Usuario, null=True)

    tipoUS = models.ForeignKey(TipoUS,related_name='uss')

    actividad = models.ForeignKey(Actividades, null=True)
    finalizado = models.BooleanField(default=False)
    options_estado_actividad = (
        ('TOD', 'Todo'),
        ('DOI', 'Doing'),
        ('DON', 'Done')
    )
    estado_actividad = models.CharField(max_length=3, choices=options_estado_actividad, default='TOD')

    history = AuditlogHistoryField()

    class Meta:
        permissions = (
            ("ver_US", "Puede ver US"),
            ("change_actividad","Puede cambiar actividad"),
            ("change_estado_actividad","Puede cambiar el estado de actividad"),
            ("repriorizar", "Puede repriorizar el US"),

        )

    def __unicode__(self):
        return unicode(self.descripcion_corta)


auditlog.register(TipoUS)
auditlog.register(Actividades)
auditlog.register(US)

US/forms.py
from django import forms
from login.models import Usuario
from models import *


class TipoUSForm(forms.Form):
    nombre = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))


class ActividadesForm(forms.Form):
    nombre = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))


class USForm(forms.Form):
    descripcion_corta = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control',}), max_length=140,
                                        help_text='Introduzca una breve descripcion del proyecto')
    descripcion_larga = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control',}), max_length=420,
                                        help_text='Introduzca una descripcion del proyecto')
    tiempo_planificado = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',}))
    valor_negocio = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',}), min_value=1,
                                       max_value=5)  # 1 a 5
    urgencia = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',}), min_value=1,
                                  max_value=5)  # 1 a 5
    usuario_asignado = forms.ModelChoiceField(queryset=Usuario.objects.none(),
                                              widget=forms.Select(attrs={'class': 'form-control',}), required=False)
    tipoUS = forms.ModelChoiceField(queryset=TipoUS.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control',}))


class CambiarActividadForm(forms.Form):
    actividad = forms.ModelChoiceField(queryset=Usuario.objects.none(),
                                       widget=forms.Select(attrs={'class': 'form-control',}), required=False)

class CambiarEstadoActividadForm(forms.Form):
    options_estado_actividad = (
        ('TOD', 'Todo'),
        ('DOI', 'Doing'),
        ('DON', 'Done')
    )
    estado_actividad = forms.ChoiceField(choices=options_estado_actividad,widget=forms.Select(attrs={'class':'form-control',}), help_text='Estado del US')

US/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.forms import formset_factory, BaseFormSet
from US.models import *
from US.forms import *
from equipo.views import enviar_notificacion

# Create your views here.
@login_required(None, 'login', '/login/')
@permission_required('US.ver_tipo_US', raise_exception=True)
def detail_tipo_us(request, pk):
    """
        Vista que permite displayar los detalles de un US seleccionado.
    """
    try:
        tipo_us = TipoUS.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/us/tipo/')

    return render(request, 'tipo_us_detail.html', {'object': tipo_us})


@login_required(None, 'login', '/login/')
@permission_required('US.ver_tipo_US', raise_exception=True)
def list_tipo_us(request):
    """
        Vista que permite listar los tipos de US.
    """
    tipo_us_list = TipoUS.objects.all()
    return render(request, 'tipo_us_list.html', {'tipo_us_list': tipo_us_list})


@login_required(None, 'login', '/login/')
@permission_required('US.add_tipous', raise_exception=True)
def create_tipo(request):
    """
        Funcion para crear tipo de US utilizando el form TipoUSForm.
        Recibe en el request el form completado, o displaya uno vacio en caso de que no se llame a
        post. Controla la validez del form antes de guardarlo como un tipo nuevo en la base de datos.
        Parametros: Recibe el request.
        Retorna:
        -El render del template tipo_us_create.html en caso de form vacio o invalido.
        -Redireccion a lista de actividades si el form es valido

        """
    if request.method == 'POST':
        form = TipoUSForm(request.POST)
        if form.is_valid():
            nombreC = form.cleaned_data['nombre']
            p = TipoUS(nombre=nombreC)
            p.save()

            return HttpResponseRedirect('/us/actividades/' + str(p.id))
    else:
        form = TipoUSForm()

    return render(request, 'tipo_us_create.html', {'form': form}, )


@login_required(None, 'login', '/login/')
@permission_required('US.delete_tipous', raise_exception=True)
def delete_tipo_us(request, pk):
    """
    Busca el tipo de us con pk igual al que es parametro y elimina si no contiene ningun US.
    Parametros: recibe el request y el pk del tipo a eliminar.
    Retorna: Redireccion a lista de tipos.
    """
    try:
        tipo_us = TipoUS.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/us/tipo/')
    if not tipo_us.uss.all():
        tipo_us.delete()

    return HttpResponseRedirect('/us/tipo/')


@login_required(None, 'login', '/login/')
@permission_required('US.change_tipous', raise_exception=True)
def update_tipo_us(request, pk):
    """
        Funcion para actualizar tipo de US utilizando el form TipoUSForm.
        Recibe en el request el form completado, o displaya uno con los datos previos del tipo en
        caso de que no se llame a post. Controla la validez del form antes de guardarlo como un tipo
         nuevo en la base de datos.
        Parametros: Recibe el request y el pk del tipo a editar.
        Retorna:
        -El render del template tipo_us_create.html en caso de form vacio o invalido.
        -Redireccion a lista de tipos si el form es valido

    """
    try:
        tipo_us = TipoUS.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/us/tipo/')

    if request.method == 'POST':
        form = TipoUSForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            tipo_us.nombre = cd['nombre']
            tipo_us.save()
            return HttpResponseRedirect('/us/tipo/' + str(tipo_us.id))
    else:
        tipo_us = TipoUS.objects.get(pk=pk)
        form = TipoUSForm(initial={'nombre': tipo_us.nombre})

    return render(request, 'tipo_us_create.html', {'form': form, 'tipo_us': tipo_us})



@login_required(None, 'login', '/login/')
@permission_required('US.add_actividades', raise_exception=True)
def create_actividad(request, pk):
    """
        Funcion para crear actividad utilizando el form ActividadesForm.
        Recibe en el request el form completado o displaya uno vacio en caso de que no se llame a post,
        y el pk del tipo de us al que pertenecen la actividad. Controla la validez del form antes de
        guardarlo como una actividad nueva en la base de datos.
        Parametros: Recibe el request.
        Retorna:
        -El render del template actividad_create.html en caso de form vacio o invalido.
        -Redireccion a lista de actividades si el form es valido.
        -Menu de creacion de tipos, si no existe el tipo.

        """
    try:
        tipo = TipoUS.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/us/tipo/create/')

    if request.method == 'POST':
        form = ActividadesForm(request.POST)
        if form.is_valid():
            actividad = Actividades()
            actividad.tipoUS = tipo
            actividad.nombre = form.cleaned_data['nombre']
            actividad.numero = Actividades.objects.filter(tipoUS__pk=pk).count() + 1
            actividad.save()

            return HttpResponseRedirect('/us/tipo/' + str(tipo.id))
    else:
        form = ActividadesForm()

    return render(request, 'actividad_create.html', {'form': form})


@login_required(None, 'login', '/login/')
def list_actividades(request, pk):
    """
        Vista que permite listar las actividades de un tipo de US.
    """
    try:
        tipo = TipoUS.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/us/tipo/create/')
    actividades_list = Actividades.objects.filter(tipoUS__pk=pk)

    return render(request, 'actividades_list.html', {'actividades_list': actividades_list, 'object': tipo})


@login_required(None, 'login', '/login/')
def create_us(request, pk):
    """
        Funcion para crear us utilizando el form USForm.
        Recibe en el request el form completadoo o displaya uno vacio en caso de que no se llame a post,
        y el pk del proyecto al que pertenece el us . Controla la validez del form antes de guardarlo
        como un us nuevo en la base de datos.
        Parametros: Recibe el request.
        Retorna:
        -El render del template us_create.html en caso de form vacio o invalido.
        -Redireccion a lista de us si el form es valido.
        -Error, si no existe el proyecto.

        """
    try:
        proyecto = Proyecto.objects.get(pk=pk)
    except:
        print 'Error'

    permisos = proyecto.equipos.filter(usuarios=request.user.id).distinct().values_list('permisos__codename',
                                                                                        flat=True)
    if ('add_us' in permisos or request.user.is_staff or request.user.has_perm('US.add_us')):
        form = USForm(request.POST or None)
        equipos = proyecto.equipos.all()
        usuarios = Usuario.objects.filter(Q(equipos__in=equipos) | Q(lider=proyecto)).distinct()

        form.fields["usuario_asignado"].queryset = usuarios
        if request.method == 'POST':
            if form.is_valid():
                us = US()
                us.proyecto = proyecto
                us.descripcion_corta = form.cleaned_data['descripcion_corta']
                us.descripcion_larga = form.cleaned_data['descripcion_larga']
                us.tiempo_planificado = form.cleaned_data['tiempo_planificado']
                us.valor_negocio = form.cleaned_data['valor_negocio']
                us.urgencia = form.cleaned_data['urgencia']
                us.usuario_asignado = form.cleaned_data['usuario_asignado']
                us.tipoUS = form.cleaned_data['tipoUS']
                if (Actividades.objects.filter(tipoUS__pk=us.tipoUS.pk).exists()):
                    us.actividad = Actividades.objects.filter(tipoUS__pk=us.tipoUS.pk).get(numero=1)

                us.save()
                usuario = us.usuario_asignado
                if (usuario.noti_cambio_estado_actividades):
                    email_noti = usuario.email
                    enviar_notificacion(email_noti, 'Se le ha asignado un US en el proyecto ' + us.proyecto.nombre +
                                            '.')
                return HttpResponseRedirect('/us/us/' + str(us.id))

        return render(request, 'us_create.html', {'form': form}, )
    else:
        raise PermissionDenied


@login_required(None, 'login', '/login/')
@permission_required('US.delete_actividades', raise_exception=True)
def delete_actividad(request, pk):
    """
    Busca la actividad con pk igual al que es parametro y la elimina.
    Parametros: recibe el request y el pk de la actividad a eliminar.
    Retorna: Redireccion a lista de actividades.
    """
    try:
        actividad = Actividades.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/us/tipo/')
    tipo_us = actividad.tipoUS
    actividad.delete()

    return HttpResponseRedirect('/us/tipo/' + str(tipo_us.id))



@login_required(None, 'login', '/login/')
def detail_us(request, pk):
    """
        Vista que permite displayar los detalles de un us seleccionado.
    """
    try:
        us = US.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/proyecto/')

    permisos = us.proyecto.equipos.filter(usuarios=request.user.id).distinct().values_list('permisos__codename',
                                                                                           flat=True)
    if ('view_us' in permisos or us.usuario_asignado == request.user or request.user.is_staff or request.user.has_perm('US.view_us')):
        if(us.proyecto.estado == 'FIN' or us.proyecto.estado == 'ANU'):
            bloqueo = 'SI'
        else:
            bloqueo = 'NO'
        return render(request, 'us_detail.html', {'object': us, 'permisos': permisos, 'bloqueo':bloqueo})
    else:

US/templates/actividad_create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Actividades</title>
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'jquery-ui-1.11.4/jquery-ui.css' %}">

{% endblock %}
{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Actividades</h1>
        <h2 class="sub-header">{% if actividad %}Modificar actividad{% else %} Crear nueva actividad{% endif %}</h2>
        <div class="col-md-offset-3 col-md-6">
            <form action="" method="post">
                <div class="form-group">
                    <label for="id_nombre">Nombre:</label>
                    {{ form.nombre }}
                    <p class="text-danger">{{ form.nombre.errors.0 }}</p>
                </div>
                 <div class="form-group">
                        <input type="submit" value="Submit" class="form-control">
                    </div>
            </form>
        </div>
    </div>
{% endblock %}

US/templates/actividades_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Actividades</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Actividades</h1>
            {% if perms.US.crear_actividades %}<a class="btn btn-primary" href="/us/actividades/create/{{ object.id }}">Crear nueva</a>{% endif %}
            <h2 class="sub-header">Listado</h2>
            <ul>
                {% for actividad in actividades_list %}
                <li><a href="/actividades/{{ actividad.pk }}">{{ actividad.nombre }}</a></li>
                {% empty %}
                <li>No existe ninguna actividad.</li>
                {% endfor %}

            </ul>
            <a class="btn btn-primary" href="/">Terminar creacion de tipo de US</a>


        </div>
{% endblock %}

US/templates/cambiar_actividad.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>US</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Actividad</h1>
        <div class="col-md-offset-3 col-md-6">
            <form action="" method="post" >
                <div class="form-group" >
                    <label for="id_actividad">Actividad:</label>
                    {{ form.actividad }}
                    <p class="text-danger">{{ form.actividad.errors.0 }}</p>
                </div>


                <div class="form-group" >
                    <label for="id_estado_actividad">Estado actividad:</label>
                    {{ form_estado.estado_actividad }}
                    <p class="text-danger">{{ form_estado.estado_actividad.errors.0 }}</p>
                </div>
                <input type="checkbox" name="finalizado" value="Si" {% if fin %}checked{% endif %}> US finalizado?<br>

                <div class="form-group">
                    <input type="submit" value="Submit" class="form-control primary">
                </div>

            </form>


        </div>

    </div>

{% endblock %}

US/templates/cambiar_estado_actividad.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>US</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Actividad</h1>
        <div class="col-md-offset-3 col-md-6">
            <form action="" method="post">
                <div class="form-group">
                    <label for="id_estado_actividad">Estado actividad:</label>
                    {{ form.estado_actividad }}
                    <p class="text-danger">{{ form.estado_actividad.errors.0 }}</p>
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" class="form-control primary">
                </div>
            </form>
        </div>

{% endblock %}

US/templates/tipo_us_create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
<title>Tipos de US</title>
<link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'jquery-ui-1.11.4/jquery-ui.css' %}">

{% endblock %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Tipos de US</h1>
            <h2 class="sub-header">{% if tipo_us %}Modificar Tipo de US {% else %} Crear nuevo Tipo de US{% endif %}</h2>
            <div class="col-md-offset-3 col-md-6">
                <form action="" method="post">
                    <div class="form-group">
                        <label for="id_nombre">Nombre:</label>
                        {{form.nombre}}
                        <p class="text-danger">{{form.nombre.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Submit" class="form-control">
                    </div>
                    </form>
            </div>
        </div>

{% endblock %}

US/templates/us_create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
<title>US</title>
<link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'jquery-ui-1.11.4/jquery-ui.css' %}">

{% endblock %}

{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">US</h1>
            <h2 class="sub-header">{% if us %}Modificar US {% else %} Crear nuevo US{% endif %}</h2>
            <div class="col-md-offset-3 col-md-6">
                <form action="" method="post">
                    <div class="form-group">
                        <label for="id_descripcion_corta">Descripcion corta:</label>
                        {{form.descripcion_corta}}
                        <p class="text-danger">{{form.descripcion_corta.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_descripcion_larga">Descripcion larga:</label>
                        {{form.descripcion_larga}}
                        <p class="text-danger">{{form.descripcion_larga.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_tiempo_planificado">Tiempo Planificado:</label>
                        {{form.tiempo_planificado}}
                        <p class="text-danger">{{form.tiempo_planificado.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_valor_negocio">Valor de negocio:</label>
                        {{form.valor_negocio}}
                        <p class="text-danger">{{form.valor_negocio.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_urgencia">Urgencia:</label>
                        {{form.urgencia}}
                        <p class="text-danger">{{form.urgencia.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_tipoUS">Tipo US:</label>
                        {{form.tipoUS}}
                        <p class="text-danger">{{form.tipoUS.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_usuario_asignado">usuario_asignado:</label>
                        {{form.usuario_asignado}}
                        <p class="text-danger">{{form.usuario_asignado.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Submit" class="form-control primary">
                    </div>
                </form>
            </div>
        </div>

{% endblock %}
{% block scripts %}
  <script src="{% static 'jquery-ui-1.11.4/jquery-ui.js' %}"></script>
{% endblock %}

US/templates/us_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>US</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">US</h1>
        {% if perms.us.add_us and bloqueo == 'NO'%}
            <a class="btn btn-primary" href="/us/us/create/{{ object.proyecto.id }}/">Crear nuevo</a>{% endif %}
        <h2 class="sub-header">Detalle</h2>
        <p>Descripcion corta: <strong>{{ object.descripcion_corta }}</strong></p>
        <p>Descripcion larga: {{ object.descripcion_larga }}</p>
        <p>Tiempo planificado: {{ object.tiempo_planificado }}</p>
        <p>Valor de negocio: {{ object.valor_negocio }}</p>
        <p>Urgencia: {{ object.urgencia }}</p>
        <p>Usuario asignado: {{ object.usuario_asignado }}</p>
        <p>Tipo US: {{ object.tipoUS }}</p>
        <p>Finalizado: {% if object.finalizado %}Si{% else %}No {% endif %}</p>
        {% if not object.finalizado %}
            <p>Actividad: {{ object.actividad | default:'Actividad no asignada' }}</p>
            <p>Estado actividad: {% if object.actividad %}{{ object.get_estado_actividad_display }}{% endif %} </p>
        {% endif %}
        {% if object.sprint.estado_sprint == 'PEN' or object.sprint == None %}
            {% if perms.US.change_us or 'change_us' in permisos and bloqueo == 'NO'%}
                <a class="btn btn-default" role="button" href="/us/us/update/{{ object.id }}">Modificar</a>{% endif %}
            {% if perms.US.delete_us and bloqueo == 'NO' or 'delete_us' in permisos and bloqueo == 'NO' %}
                <a class="btn btn-danger" role="button" href="/us/us/delete/{{ object.id }}">Eliminar</a>{% endif %}
        {% elif object.sprint.estado_sprint == 'INI' %}
            {% if perms.US.change_actividad or 'change_actividad' in permisos and bloqueo == 'NO'%}
                <a class="btn btn-default" role="button" href="/us/us/cambiar_actividad/{{ object.id }}">Cambiar
                    actividad</a>{% endif %}
            {% if not object.finalizado %}
                {% if object.usuario_asignado == user and bloqueo == 'NO' or perms.US.change_estado_actividad and bloqueo == 'NO' or 'change_estado_actividad' in permisos and bloqueo == 'NO'%}
                    <a class="btn btn-default" role="button" href="/us/us/cambiar_estado_actividad/{{ object.id }}">Cambiar
                        estado de actividad</a>
                {% endif %}
            {% endif %}
        {% elif object.sprint.estado_sprint == 'FIN' and not object.finalizado or not obejct.sprint == None %}
        {% if perms.US.repriorizar or 'repriorizar' in permisos and bloqueo == 'NO'%}
            <p><Strong>El sprint que contenia a este US ha finalizado, si desea volver a colocar este US con prioridad
                alta presione <a href="/us/us/repriorizar/{{ object.id }}">aqui</a></Strong></p>
        {% endif %}

        {% else %}
            <p><strong>Sprint finalizado</strong></p>
        {% endif %}
    </div>
{% endblock %}