US/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^tipo/(?P<pk>[0-9]+)/$', detail_tipo_us, name='tipo_us_detail'),
    url(r'^tipo/$', list_tipo_us),
    url(r'^tipo/create/$',create_tipo),
    url(r'^tipo/delete/(?P<pk>[0-9]+)/$', delete_tipo_us, name='tipo_us_delete'),
    url(r'^tipo/update/(?P<pk>[0-9]+)/$', update_tipo_us, name='tipo_us_update'),
    url(r'^actividades/create/(?P<pk>[0-9]+)/$', create_actividad, name='actividad_create'),
    url(r'^actividades/(?P<pk>[0-9]+)/$', list_actividades, name='actividad_list'),
    url(r'^actividades/delete/(?P<pk>[0-9]+)/$', delete_actividad, name='actividad_delete'),
    url(r'^us/create/(?P<pk>[0-9]+)/$', create_us, name='us_create'),
    url(r'^us/delete/(?P<pk>[0-9]+)/$', delete_us, name='us_delete'),
    url(r'^us/update/(?P<pk>[0-9]+)/$', update_us, name='us_update'),
    url(r'^us/(?P<pk>[0-9]+)/$', detail_us, name='us_detail'),
    url(r'^us/cambiar_actividad/(?P<pk>[0-9]+)/$', cambiar_actividad, name='cambiar_actividad'),
    url(r'^us/cambiar_estado_actividad/(?P<pk>[0-9]+)/$', cambiar_estado_actividad, name='cambiar_estado_actividad'),
    url(r'^us/repriorizar/(?P<pk>[0-9]+)/$', repriorizar, name='repriorizar')

]

login/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.dashboard),
    url(r'^login/', views.login_user),
    url(r'^logout/',views.logout_user),
    url(r'^delete_telefono/(?P<pk>[0-9]+)/$', views.delete_telefono, name='delete_telefono'),
    url(r'^modificar_telefono/(?P<pk>[0-9]+)/$', views.modificar_telefono, name='modificar_telefono'),
    url(r'configuracion/',views.configuracion,name='configuracion'),
    url(r'log/',views.log_general,name='log')
]

sistema_proyectos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'',include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^proyecto/', include('proyecto.urls')),
    url(r'^cliente/', include ('cliente.urls')),
    url(r'^equipo/', include('equipo.urls')),
    url(r'^sprint/', include('sprint.urls')),
    url(r'^us/', include ('US.urls')),
]

equipo/models.py
# encoding:utf-8

from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.db import models

from login.models import Usuario
from proyecto.models import Proyecto


# Create your models here.


class Equipo(models.Model):
    """
    Clase Equipo que heredea del modelo Group de django.
    proyecto = proyecto al que pertenece el equipo.
    usuarios = usuarios miembros del equipo.
    """
    nombre = models.CharField(max_length=80)
    permisos = models.ManyToManyField(Permission, blank=True)
    proyecto = models.ForeignKey(Proyecto, null=True, related_name='equipos')
    usuarios = models.ManyToManyField(Usuario, related_name='equipos')

    history = AuditlogHistoryField()

    def __unicode__(self):
        return self.nombre

auditlog.register(Equipo)

login/models.py
from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.contrib.auth.models import User, AbstractUser
from django.db import models

from cliente.models import Cliente


# Create your models here.

class Usuario(AbstractUser):
    """
    Se crea la clase Usuario que hereda del modelo User de django, para agregarle mas atributos.
    cedula = numero de cedula del usuario.
    direccion = direccion del usuario.
    """
    cedula = models.PositiveIntegerField(default=0)
    direccion = models.TextField(max_length=50, blank=True, null=False)

    # Configuraciones de usuario
    hora_notificaciones = models.TimeField(null=True, default="00:00:00")
    formato = (
        ('htm', 'HTML'),
        ('txt', 'Texto Plano')
    )
    formato_notificaciones = models.CharField(max_length=3, choices=formato, default='htm', help_text='Formato')
    noti_creacion_proyecto = models.BooleanField(default=False)
    noti_creacion_usuario = models.BooleanField(default=False)
    noti_creacion_equipos = models.BooleanField(default=False)
    noti_cambio_estado_actividades = models.BooleanField(default=False)
    noti_us_asignado = models.BooleanField(default=False)
    noti_cambio_actividades = models.BooleanField(default=False)



    history = AuditlogHistoryField()

    def __unicode__(self):
        return self.username


auditlog.register(Usuario)


class Telefono(models.Model):
    """
    Se crea la clase Telefono que hereda del moodelo Model de django.
    numero : Integer que representa al telefono.
    cliente : CCliente asociado al telefono.
    usuario : Usuario asociado al telefono.

    """
    numero = models.PositiveIntegerField(default=0)
    cliente = models.ForeignKey(Cliente, null=True, related_name="telefonos")
    usuario = models.ForeignKey(Usuario, null=True, related_name="telefonos")

    history = AuditlogHistoryField()

    def __unicode__(self):
        return str(self.numero)


auditlog.register(Telefono)

proyecto/models.py
#encoding:utf-8
from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.utils import timezone
from django.db import models
from login.models import Usuario
from cliente.models import Cliente

class Proyecto (models.Model):
    """
    Se crea la clase Proyecto, que hereda de Model de django, con los siguientes atributos:
    nombre : El nombre del proyecto.
    fechaCreacion : La fecha en la cual se creo el proyecto.
    fechaInicio : La fecha en la cual se inicia el proyecto.
    fechaFin : La fecha en la cual se termino el proyecto.
    liderProyecto : Usuario lider del proyecto.
    descripcion : breve descripcion del proyecto.
    estado : Estado actual del proyecto, puede ser Pendiente, Anulado, Activo o Finalizado.
    Obvservaciones : Ciertas observaciones del proyecto.
    cliente : Cliente que solicito el proyecto.
    activo : variable que determina un estado de "eliminado" para el Proyecto.


    Metodos:
    hacerLider : Establece un Usuario como lider del proyecto.
    """
    opciones_estado = (
        ('PEN', 'Pendiente'),
        ('ANU', 'Anulado'),
        ('ACT', 'Activo'),
        ('FIN', 'Finalizado'),)
    nombre = models.CharField(max_length=50, null=False)
    fecha_creacion = models.DateField(auto_now=True)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    lider_proyecto = models.ForeignKey(Usuario, related_name='lider')
    descripcion = models.TextField(max_length=140, help_text='Introduzca una breve reseña del proyecto', null=True)
    estado = models.CharField(max_length=3, choices=opciones_estado, default='PEN', help_text='Estado del proyecto')
    observaciones = models.TextField(max_length=140, null=True, default='No hay observaciones')
    cliente = models.ForeignKey(Cliente, on_delete= models.DO_NOTHING)
    activo = models.BooleanField(default=True)

    history = AuditlogHistoryField()

    class Meta:
        permissions = (
            ("view_proyecto", "Puede ver proyecto"),
            ("change_estado", "Puede cambiar el estado del proyecto"),
            ("view_log", "Puede cambiar el estado del proyecto"),
        )

    def hacerLider (self, lider):
        self.lider_proyecto=lider
        self.save()

    def __unicode__ (self):
        return self.nombre

auditlog.register(Proyecto)

login/forms.py
#encoding:utf-8
from django import forms

class ConfiguracionForm(forms.Form):
    """
    Clases para crear las configuraciones
    """
    """hora_notificaciones = forms.TimeField(widget=forms.TimeInput(attrs={'class':'form-control time-picker'}),required=True)
    formato = (
        ('htm', 'HTML'),
        ('txt', 'Texto Plano')
    )
    formato_notificaciones = forms.ChoiceField(choices=formato,widget=forms.Select(attrs={'class':'form-control'}),help_text='Formato')
    """
    email_noti = forms.EmailField(required=True)
    noti_creacion_proyecto = forms.BooleanField(widget=forms.CheckboxInput(),
                                                help_text="Notificacion de proyectos creados.",required=False)

    noti_creacion_equipo = forms.BooleanField(widget=forms.CheckboxInput(),
                                              help_text="Notificacion de equipos creados.",required=False)
    noti_cambio_estado_actividades = forms.BooleanField(widget=forms.CheckboxInput(),
                                                help_text="Notificacion de cambio de estado de actividades.",
                                                required=False)
    noti_us_asignado = forms.BooleanField(widget=forms.CheckboxInput(),
                                               help_text="Notificacion de asignacion a un US.", required=False)
    noti_cambio_actividades = forms.BooleanField(widget=forms.CheckboxInput(),
                                                 help_text="Notificacion de cambio de actividades.",
                                              required=False)

login/views.py
from auditlog.models import LogEntry
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from cliente.forms import TelefonoForm
from login.forms import ConfiguracionForm
from models import Telefono, Usuario
from proyecto.models import Proyecto


def login_user(request):
    """
    Funcion de login de usuario.

    Variables
    username = Nombre de usuario.
    password = Clave de usuario.
    state = Estado del login, puede ser logueado, esperando datos, o demostrar un error de datos incorrectos.

    La funcion recibe en el request los datos de usuario determina si es correcta y esta activada.
    La funcion retorna por medio del context el estado del login y el username.
    """
    state = ""
    if request.user.is_authenticated():
        state = "Esta logueado como " + str(request.user.username)

    username = password = ""
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                state = "Has iniciado sesion correctamente!"
                return redirect('/')
            else:
                state = "La cuenta no esta activa. Contacte con el administrador."
        else:
            state = "Su nombre de usuario o password es incorrecto/a."

    return render(request, 'login.html', {'state': state, 'username': username})


@login_required(None, 'login', '/login/')
def logout_user(request):
    """Funcion que cierra sesion de un usuario y redirecciona a la pantalla de login."""
    logout(request)
    return redirect("/")


@login_required(None, 'login', '/login/')
def dashboard(request):
    """Funcion que muestra el menu principal del sistema"""
    user = request.user
    if user.equipos:
        result = []
        proyectos = Proyecto.objects.filter(
            Q(activo=True, equipos__in=user.equipos.values('id')) | Q(activo=True, lider_proyecto=user)).distinct()

        for p in proyectos:
            permisos = []
            equipos = p.equipos.all().values_list('permisos__codename',
                                                  flat=True)  # .filter(usuarios=user.id).distinct().values_list('permisos__codename', flat=True)
            permisos.extend(equipos)
            result.append([p, permisos])

    return render(request, 'dashboard.html', {'proyectos': result})


@login_required(None, 'login', '/login/')
def delete_telefono(request, pk):
    try:
        telefono = Telefono.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/')

    if telefono.cliente:
        aux = telefono.cliente
        telefono.delete()
        return HttpResponseRedirect('/cliente/' + str(aux.id))
    else:
        aux = telefono.usuario
        telefono.delete()
        return HttpResponseRedirect('/usuario/' + str(aux.id))


@login_required(None, 'login', '/login/')
def modificar_telefono(request, pk):
    try:
        t = Telefono.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        form = TelefonoForm(request.POST)
        if form.is_valid():
            telefono = form.cleaned_data['telefono']
            t.numero = telefono
            t.save()
            if t.cliente:
                return HttpResponseRedirect('/cliente/' + str(t.cliente.id))
            else:
                return HttpResponseRedirect('/usuario/' + str(t.usuario.id))
    else:
        form = TelefonoForm({'telefono': t.numero})

    return render(request, 'edit_telefono.html', {'form': form})


@login_required(None, 'login', '/login/')
def configuracion(request):
    """funcion para la configuracion del sistema"""

    try:
        usuario = Usuario.objects.get(pk=request.user.id)
    except:
        return HttpResponseRedirect('/login/')
    es_lider = False
    if request.method == 'POST':
        form = ConfiguracionForm(request.POST)
        if form.is_valid():
            usuario.email = form.cleaned_data['email_noti']
            usuario.noti_creacion_proyecto = form.cleaned_data['noti_creacion_proyecto']
            usuario.noti_creacion_equipos = form.cleaned_data['noti_creacion_equipo']
            usuario.noti_cambio_estado_actividades = form.cleaned_data['noti_cambio_estado_actividades']
            usuario.noti_cambio_actividades = form.cleaned_data['noti_cambio_actividades']
            usuario.noti_us_asignado = form.cleaned_data['noti_us_asignado']
            usuario.save()
            return HttpResponseRedirect('/')
    else:
        Usuario.objects.get(pk=request.user.id)
        user = request.user

        if user.equipos:

            proyectos = Proyecto.objects.filter(
                Q(activo=True, equipos__in=user.equipos.values('id')) | Q(activo=True, lider_proyecto=user)).distinct()
            if (proyectos.count()>0):
                es_lider=True


        form = ConfiguracionForm(initial={
                                  'email_noti': usuario.email,
                                  'noti_creacion_proyecto': usuario.noti_creacion_proyecto,
                                  'noti_creacion_equipo': usuario.noti_creacion_equipos,
                                  'noti_cambio_actividades': usuario.noti_cambio_actividades,
                                  'noti_cambio_estado_actividades': usuario.noti_cambio_estado_actividades,
                                  'noti_us_asignado':usuario.noti_us_asignado,
                                  })
    return render(request, 'configuracion.html', {'form': form, 'usuario': usuario,'es_lider':es_lider})


@login_required(None, 'login', '/login/')
def log_general(request):
    log_g = LogEntry.objects.all()

    return render(request, 'log.html', {'log_g': log_g})

login/templates/configuracion.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Configuraciones</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'timepicker/jquery.timepicker.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <h1 class="page-header">Configuraciones</h1>
                <h2 class="sub-header">Configuraciones de usuario y sistema</h2>
                <div class="col-md-offset-4 col-md-4">
                    <form action="" method="post">
                        <!--
                        <div class="form-group">
                            <label for="id_hora_notificaciones">Hora de notificacion</label>
                            {{ form.hora_notificaciones }}
                            <p class="text-danger">{{ form.hora_notificaciones.errors.0 }}</p>
                        </div>
                        <div class="form-group">
                            <label for="id_formato_notificaciones">Formato de notificaciones</label>
                            {{ form.formato_notificaciones }}
                            <p class="text-danger">{{ form.formato_notificaciones.errors.0 }}</p>
                        </div>
                        -->
                        <div class="form-group">
                            <label>{{ form.email_noti }}Ingrese su e-mail</label>

                            <p class="text-danger">{{ form.email_noti.errors.0 }}</p>
                        </div>

                        {% if perms.proyecto.add_proyecto %}
                        <div class="checkbox">
                            <label>{{ form.noti_creacion_proyecto }}Notificar por creacion de Proyecto</label>
                        </div>
                        {% endif %}
                        {% if perms.equipo.add_equipo %}
                        <div class="checkbox">
                            <label>{{ form.noti_creacion_equipo }}Notificar por creacion de Equipo</label>
                        </div>
                        {% endif %}
                        {% if es_lider %}
                        <div class="checkbox">
                            <label>{{ form.noti_cambio_estado_actividades }}Notificar por cambio de estado de actividades</label>

                            <p class="text-danger">{{ form.noti_cambio_estado_actividades.errors.0 }}</p>
                        </div>
                        {% endif %}


                        <div class="checkbox">
                            <label>{{ form.noti_cambio_actividades }}Notificar por cambio de actividades</label>

                            <p class="text-danger">{{ form.noti_cambio_actividades.errors.0 }}</p>
                        </div>

                        <div class="checkbox">
                            <label>{{ form.noti_us_asignado }}Notificar por asignacion de US al usuario</label>

                            <p class="text-danger">{{ form.noti_us_asignado.errors.0 }}</p>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Submit" class="form-control primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'timepicker/jquery.timepicker.min.js' %}"></script>
    <script type="text/javascript">
    $('.time-picker').timepicker({ 'timeFormat': 'H:i:s' });

    </script>
{% endblock %}

login/templates/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Sistema Proyectos</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>
          <h2 class="sub-header">Mis proyectos</h2>
          {% if proyectos %}
          <table class="table table-responsive">
            <thead>
            <tr>
              <th>Nombre</th>
              <th>Lider del Proyecto</th>
              <th>Cliente</th>
              <th>Estado</th>
            </tr>
            </thead>
            <tbody>
            {% for proyecto,permisos in proyectos %}

            <tr>
              <td>{% if 'view_proyecto' in permisos or proyecto.lider_proyecto == user %}<a href="/proyecto/{{proyecto.id}}">{{proyecto.nombre}}</a>{% else %}{{proyecto.nombre}}  {% endif %}</td>
              <td>{{proyecto.lider_proyecto}}</td>
              <td>{{proyecto.cliente}}</td>
              <td>{{proyecto.get_estado_display}}</td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
          {% else %}
          <p>No estas trabajando en ningun proyecto.</p>
          {% endif %}



          </div>

{% endblock %}

login/templates/log.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Log General</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Log General</h1>
        <h2 class="sub-header">Listado</h2>
        <table class="table table-responsive">
            <thead>
            <tr>
                <th>Actor</th>
                <th>Fecha</th>
                <th>Accion</th>
            </tr>
            </thead>
            <tbody>
            {% for log in log_g %}
                <tr>
                    <td>{{ log.actor }}</td>
                    <td>{{ log.timestamp }}</td>
                    <td>{{ log}}</td>
                </tr>
            {% empty %}
                No existe ningun proyecto.
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

login/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Log in</title>
{% endblock %}}
{% block login %}
<div class="container" style="margin-top: 15%">
    {% if user.is_authenticated %}
        <div class="col-md-offset-4">
        {{ state }}
        <a href="/logout/">Logout</a>
        </div>
    {% else %}
        <div class="col-md-offset-4 col-md-4">

            <form method="post">
                <h3 style="text-align: center">Login</h3>
                <div class="form-group">
                        <input type="text" class="form-control" id="username" name="username" placeholder="Usuario" required>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña" required>
                </div>

                <div class="danger">
                    <p class="text-danger">{{ state }}</p>
                </div>
                <div class="form-group">
                    <input class="btn btn-primary form-control" type="submit" value="Log In">
                </div>
            </form>
        </div>
            </div>
    {% endif %}
{% endblock%}