US/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^tipo/(?P<pk>[0-9]+)/$', detail_tipo_us, name='tipo_us_detail'),
    url(r'^tipo/$', list_tipo_us),
    url(r'^tipo/create/$',create_tipo),
    url(r'^tipo/delete/(?P<pk>[0-9]+)/$', delete_tipo_us, name='tipo_us_delete'),
    url(r'^tipo/update/(?P<pk>[0-9]+)/$', update_tipo_us, name='tipo_us_update'),
    url(r'^actividades/create/(?P<pk>[0-9]+)/$', create_actividad, name='actividad_create'),
    url(r'^actividades/(?P<pk>[0-9]+)/$', list_actividades, name='actividad_list'),
    url(r'^actividades/delete/(?P<pk>[0-9]+)/$', delete_actividad, name='actividad_delete'),
    url(r'^us/create/(?P<pk>[0-9]+)/$', create_us, name='us_create'),
    url(r'^us/delete/(?P<pk>[0-9]+)/$', delete_us, name='us_delete'),
    url(r'^us/update/(?P<pk>[0-9]+)/$', update_us, name='us_update'),
    url(r'^us/(?P<pk>[0-9]+)/$', detail_us, name='us_detail'),
    url(r'^us/cambiar_actividad/(?P<pk>[0-9]+)/$', cambiar_actividad, name='cambiar_actividad'),
    url(r'^us/cambiar_estado_actividad/(?P<pk>[0-9]+)/$', cambiar_estado_actividad, name='cambiar_estado_actividad'),
    url(r'^us/repriorizar/(?P<pk>[0-9]+)/$', repriorizar, name='repriorizar')

]

cliente/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', list_cliente,name='cliente_list'),
    url(r'^create/$',create_cliente, name='cliente_create'),
    url(r'update/(?P<pk>[0-9]+)/$', update_cliente, name='cliente_update'),
    url(r'add_telefono/(?P<pk>[0-9]+)/$', create_telefono, name='telefono_create'),
    url(r'delete/(?P<pk>[0-9]+)/$', delete_cliente , name='cliente_delete'),
    url(r'^(?P<pk>[0-9]+)/$', detail_cliente, name='cliente_detail'),
]

sistema_proyectos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'',include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^proyecto/', include('proyecto.urls')),
    url(r'^cliente/', include ('cliente.urls')),
    url(r'^equipo/', include('equipo.urls')),
    url(r'^sprint/', include('sprint.urls')),
    url(r'^us/', include ('US.urls')),
]

cliente/models.py
#encoding:utf-8

from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.db import models
# Create your models here.
class Cliente (models.Model):
    """
    Se crea la clase Cliente, que hereda de Model de django, con los siguientes atributos:
    nombre : El nombre del cliente.
    direccion : La direccion el cliente.
    email: Correo electronico del cliente.
    activo: variable que determina un estado de "eliminado" para el Cliente.

    """
    nombre = models.CharField(max_length=100)
    direccion = models.CharField (max_length=100)
    email = models.EmailField()
    activo = models.BooleanField(default=True)

    history = AuditlogHistoryField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        permissions = (
            ("view_cliente", "Puede ver cliente"),
        )

auditlog.register(Cliente)

login/models.py
from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.contrib.auth.models import User, AbstractUser
from django.db import models

from cliente.models import Cliente


# Create your models here.

class Usuario(AbstractUser):
    """
    Se crea la clase Usuario que hereda del modelo User de django, para agregarle mas atributos.
    cedula = numero de cedula del usuario.
    direccion = direccion del usuario.
    """
    cedula = models.PositiveIntegerField(default=0)
    direccion = models.TextField(max_length=50, blank=True, null=False)

    # Configuraciones de usuario
    hora_notificaciones = models.TimeField(null=True, default="00:00:00")
    formato = (
        ('htm', 'HTML'),
        ('txt', 'Texto Plano')
    )
    formato_notificaciones = models.CharField(max_length=3, choices=formato, default='htm', help_text='Formato')
    noti_creacion_proyecto = models.BooleanField(default=False)
    noti_creacion_usuario = models.BooleanField(default=False)
    noti_creacion_equipos = models.BooleanField(default=False)
    noti_cambio_estado_actividades = models.BooleanField(default=False)
    noti_us_asignado = models.BooleanField(default=False)
    noti_cambio_actividades = models.BooleanField(default=False)



    history = AuditlogHistoryField()

    def __unicode__(self):
        return self.username


auditlog.register(Usuario)


class Telefono(models.Model):
    """
    Se crea la clase Telefono que hereda del moodelo Model de django.
    numero : Integer que representa al telefono.
    cliente : CCliente asociado al telefono.
    usuario : Usuario asociado al telefono.

    """
    numero = models.PositiveIntegerField(default=0)
    cliente = models.ForeignKey(Cliente, null=True, related_name="telefonos")
    usuario = models.ForeignKey(Usuario, null=True, related_name="telefonos")

    history = AuditlogHistoryField()

    def __unicode__(self):
        return str(self.numero)


auditlog.register(Telefono)

cliente/forms.py
from django import forms


class ClienteForm(forms.Form):
    """
    Form para editar o crear cliente.
    """
    nombre = forms.CharField(max_length=100, label='Nombre', required=True)
    direccion = forms.CharField(max_length=100, label='Direccion', required=True)
    email = forms.EmailField(label='Email',required=True)

class TelefonoForm(forms.Form):
    telefono = forms.IntegerField(min_value=0,required=True, widget=forms.NumberInput(attrs={'class':'form-control',}))

cliente/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.views.generic import CreateView,ListView,UpdateView, DetailView
from cliente.models import Cliente
from login.models import Telefono
from django.http import HttpResponseRedirect
from cliente.forms import *


# Create your views here.
@login_required(None, 'login', '/login/')
@permission_required('cliente.view_cliente',raise_exception=True)
def list_cliente (request):
    cliente_list = Cliente.objects.filter(activo=True)

    return render(request,'cliente_list.html', {'cliente_list': cliente_list})

@login_required(None, 'login', '/login/')
@permission_required('cliente.view_cliente',raise_exception=True)
def detail_cliente(request,pk):
    cliente = get_object_or_404(Cliente,pk=pk)

    return render(request, 'cliente_detail.html', {'object': cliente})


@login_required(None, 'login', '/login/')
@permission_required('login.add_telefono',raise_exception=True)
def create_telefono (request, pk):
    cliente = get_object_or_404(Cliente,pk=pk)

    if request.method == 'POST':
        form = TelefonoForm(request.POST)
        if form.is_valid():
            telefono = form.cleaned_data['telefono']
            t = Telefono()
            t.numero = telefono
            t.cliente = cliente
            t.save()
            return HttpResponseRedirect('/cliente/'+str(cliente.id))
    else:
        form = TelefonoForm()

    return render(request,'edit_telefono.html', {'form': form})

@login_required(None, 'login', '/login/')
@permission_required('cliente.add_cliente',raise_exception=True)
def create_cliente (request):
    """
        Funcion para crear cliente utilizando el form ClienteForm.
        Recibe en el request el form completado, o displaya uno vacio en caso de que no se llame a
        post. Controla la validez del form antes de guardarlo como un cliente nuevo en la base de datos.
        Parametros: Recibe el request.
        Retorna:
        -El render del template cliente_create.html en caso de form vacio o invalido.
        -Redireccion a lista de clientes si el form es valido

    """
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            nombreC = form.cleaned_data['nombre']
            direccionC = form.cleaned_data['direccion']
            emailC = form.cleaned_data['email']
            p = Cliente(nombre = nombreC, direccion = direccionC, email= emailC)
            p.save()
            return HttpResponseRedirect('/cliente/'+str(p.id))
    else:
        form = ClienteForm()
    return render(request,'cliente_create.html', {'form': form},context_instance=RequestContext(request))

@login_required(None, 'login', '/login/')
@permission_required('cliente.change_cliente',raise_exception=True)
def update_cliente (request, pk):
    """
        Funcion para actualizar cliente utilizando el form ClienteForm.
        Recibe en el request el form completado, o displaya uno con los datos previos del cliente en
        caso de que no se llame a post. Controla la validez del form antes de guardarlo como un cliente
        nuevo en la base de datos.
        Parametros: Recibe el request y el pk del cliente a editar.
        Retorna:
        -El render del template cliente_create.html en caso de form vacio o invalido.
        -Redireccion a lista de clientes si el form es valido

    """
    cliente = get_object_or_404(Cliente,pk=pk)

    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente.nombre= form.cleaned_data['nombre']
            cliente.direccion= form.cleaned_data['direccion']
            cliente.email = form.cleaned_data['email']
            cliente.save()
            return HttpResponseRedirect('/cliente/')
    else:
        cliente = Cliente.objects.get(pk = pk)
        form = ClienteForm(initial={'nombre':cliente.nombre, 'direccion':cliente.direccion, 'email':cliente.email})
        return render(request, 'cliente_create.html', {'form': form,'cliente':cliente},context_instance=RequestContext(request))

@login_required(None, 'login', '/login/')
@permission_required('cliente.delete_cliente', raise_exception=True)
def delete_cliente(request, pk):
    """
        Busca el cliente con pk igual al que es parametro y cambia su estado activo a False.
        Parametros: recibe el request y el pk del cliente a eliminar.
        Retorna: Redireccion a lista de clientes.
    """
    cliente = get_object_or_404(Cliente,pk=pk)

    cliente.activo = False
    cliente.save()

    return HttpResponseRedirect('/cliente/')

cliente/templates/cliente_create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Cliente</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Clientes</h1>
            <h2 class="sub-header">{% if cliente %}Modificar cliente {% else %} Crear nuevo cliente{% endif %}</h2>
            <div class="col-md-offset-3 col-md-6">
            <form action="" method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="id_nombre">Nombre:</label>
                <input class="form-control" id="id_nombre" maxlength="100" name="nombre" type="text" value="{{form.nombre.value | default:''}}" />
                    <p class="text-danger">{{form.nombre.errors.0}}</p>
                </div>
                <div class="form-group">
                    <label for="id_direccion">Direccion:</label>
                    <input class="form-control" id="id_direccion" maxlength="100" name="direccion" type="text" value="{{form.direccion.value | default:''}}" />
                    <p class="text-danger">{{form.direccion.errors.0}}</p>
                </div>
                <div class="form-group">
                    <label for="id_email">Email:</label>
                    <input class="form-control" id="id_email" name="email" type="email" value="{{form.email.value | default:''}}"/>
                    <p class="text-danger">{{form.email.errors.0}}</p>
                </div>
                <div class="form-group">
                <input class="form-control" type="submit" value="Submit">
                    </div>
            </form>
            </div>
        </div>

{% endblock %}



</body>
</html>

cliente/templates/cliente_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Cliente</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Clientes</h1>
            {% if perms.cliente.add_cliente %}<a class="btn btn-primary" href="/cliente/create/">Crear nuevo</a>{% endif %}

            <h2 class="sub-header">Detalle</h2>
            <p>Nombre: <strong>{{ object.nombre }}</strong></p>
            <p>Email: {{ object.email }}</p>
            <p>Direccion: {{ object.direccion }}</p>
            {% if perms.cliente.change_cliente %}<a class="btn btn-default" role="button" href="/cliente/update/{{ object.id }}">Modificar</a>{% endif %}
            {% if perms.cliente.delete_cliente %}<a class="btn btn-danger" role="button" href="/cliente/delete/{{ object.id }}">Eliminar</a>{% endif %}
            <h2 class="sub-header">Teléfonos</h2>
            {% if perms.login.add_telefono %}<a class="btn btn-primary" href="/cliente/add_telefono/{{object.id}}">Crear nuevo</a>{% endif %}
            <br>
            <ul>
                {% for tel in object.telefonos.all %}
                <li>{{tel.numero}}{% if perms.login.change_telefono %} <a href="/modificar_telefono/{{tel.id}}" class="text-primary">modificar</a>{% endif %}{% if perms.login.delete_telefono %} <a href="/delete_telefono/{{tel.id}}" class="text-danger">delete</a>{% endif %}</li>
                {% endfor %}
            </ul>


        </div>
{% endblock %}

cliente/templates/cliente_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Cliente</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Clientes</h1>
            {% if perms.cliente.add_cliente %}<a class="btn btn-primary" href="/cliente/create/">Crear nuevo</a>{% endif %}
            <h2 class="sub-header">Listado</h2>
            <ul>
                {% for cliente in cliente_list %}
                <li><a href="/cliente/{{ cliente.pk }}">{{ cliente.nombre }}</a></li>
                {% empty %}
                <li>No existe ningun cliente.</li>
                {% endfor %}
            </ul>
        </div>
{% endblock %}

cliente/templates/edit_telefono.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Cliente</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="col-md-offset-4 col-md-4">
            <form action="" method="post">{% csrf_token %}
            <div class="form-group">
                <label>Telefono: </label>
                {{form.telefono}}
                <p class="text-danger">{{form.telefono.errors.0}}</p>
            </div>
            <div class="form-group">
                <input class="form-control" type="submit" value="Submit">
            </div>
        </form>
            </div>
    </div>
{% endblock %}