US/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^tipo/(?P<pk>[0-9]+)/$', detail_tipo_us, name='tipo_us_detail'),
    url(r'^tipo/$', list_tipo_us),
    url(r'^tipo/create/$',create_tipo),
    url(r'^tipo/delete/(?P<pk>[0-9]+)/$', delete_tipo_us, name='tipo_us_delete'),
    url(r'^tipo/update/(?P<pk>[0-9]+)/$', update_tipo_us, name='tipo_us_update'),
    url(r'^actividades/create/(?P<pk>[0-9]+)/$', create_actividad, name='actividad_create'),
    url(r'^actividades/(?P<pk>[0-9]+)/$', list_actividades, name='actividad_list'),
    url(r'^actividades/delete/(?P<pk>[0-9]+)/$', delete_actividad, name='actividad_delete'),
    url(r'^us/create/(?P<pk>[0-9]+)/$', create_us, name='us_create'),
    url(r'^us/delete/(?P<pk>[0-9]+)/$', delete_us, name='us_delete'),
    url(r'^us/update/(?P<pk>[0-9]+)/$', update_us, name='us_update'),
    url(r'^us/(?P<pk>[0-9]+)/$', detail_us, name='us_detail'),
    url(r'^us/cambiar_actividad/(?P<pk>[0-9]+)/$', cambiar_actividad, name='cambiar_actividad'),
    url(r'^us/cambiar_estado_actividad/(?P<pk>[0-9]+)/$', cambiar_estado_actividad, name='cambiar_estado_actividad'),
    url(r'^us/repriorizar/(?P<pk>[0-9]+)/$', repriorizar, name='repriorizar')

]

proyecto/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^$', list_proyecto, name='proyecto_list'),
    url(r'^create/$',create_proyecto),
    url(r'update/(?P<pk>[0-9]+)/$', update_proyecto, name='proyecto_update'),
    url(r'cambiar_estado/(?P<pk>[0-9]+)/$', cambiar_estado, name='proyecto_estado'),
    url(r'delete/(?P<pk>[0-9]+)/$', delete_proyecto, name='proyecto_delete'),
    url(r'^(?P<pk>[0-9]+)/$', detail_proyecto, name='proyecto_detail'),
    url(r'log_proyecto/(?P<pk>[0-9]+)/$',log_proyecto,name='log_proyecto')
]

sistema_proyectos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'',include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^proyecto/', include('proyecto.urls')),
    url(r'^cliente/', include ('cliente.urls')),
    url(r'^equipo/', include('equipo.urls')),
    url(r'^sprint/', include('sprint.urls')),
    url(r'^us/', include ('US.urls')),
]

US/models.py
from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.db import models
from proyecto.models import Proyecto
from sprint.models import Sprint
from login.models import Usuario

# Create your models here.


class TipoUS(models.Model):
    """
    Clase TipoUS que hereda de models.Model
    nombre = El nombre del tipo de US
    """
    nombre = models.TextField(default="")

    history = AuditlogHistoryField()
    class Meta:
        permissions = (
            ("ver_tipo_US", "Puede ver tipos de US"),
        )

    def __unicode__(self):
        return self.nombre



class Actividades(models.Model):
    """
    Clase Actividades que hereda de models.Model
    nombre = Nombre de la actividad
    tipoUS= Tipo dee US al que pertenece la actividad.
    """

    nombre = models.TextField(default="")
    tipoUS = models.ForeignKey(TipoUS, related_name='actividades')
    numero = models.IntegerField(default=0)

    history = AuditlogHistoryField()

    class Meta:
        permissions = (
            ("ver_actividades", "Puede ver actividades"),
            ("crear_actividades", "Puede crear actividades"),
        )

    def __unicode__(self):
        return self.nombre

class US(models.Model):
    """
    Clase US que hereda de models.Model.
    sprint = Sprint al que esta asignado el US.
    proyecto = Proyecto al que pertenece el US.
    descripcion_corta = Descripcion corta del US.
    descripcion_larga = Descripcion larga del US.
    tiempo_planificado = Tiempo aproximado que tomaria terminar el US.
    valor_negocio = Entero que representa el valor del US en el proyecto.
    urgencia = Entero que representa la urgencia para terminar el US.
    tipoUS = Tipo de US del US, define el flujo a utilizar.
    actividad = Actividad actual del US dentro del flujo.
    estado_actividad = Estado de la actividad actual.
    """
    sprint = models.ForeignKey(Sprint, null=True,blank=True, related_name='uss')
    proyecto = models.ForeignKey(Proyecto,null=True,related_name='uss')
    descripcion_corta = models.TextField(default="")
    descripcion_larga = models.TextField(default="")
    tiempo_planificado = models.IntegerField(default=0)
    valor_negocio = models.IntegerField(default=1)  # 0 a 4
    urgencia = models.IntegerField(default=1)  # 0 a 4
    usuario_asignado = models.ForeignKey(Usuario, null=True)

    tipoUS = models.ForeignKey(TipoUS,related_name='uss')

    actividad = models.ForeignKey(Actividades, null=True)
    finalizado = models.BooleanField(default=False)
    options_estado_actividad = (
        ('TOD', 'Todo'),
        ('DOI', 'Doing'),
        ('DON', 'Done')
    )
    estado_actividad = models.CharField(max_length=3, choices=options_estado_actividad, default='TOD')

    history = AuditlogHistoryField()

    class Meta:
        permissions = (
            ("ver_US", "Puede ver US"),
            ("change_actividad","Puede cambiar actividad"),
            ("change_estado_actividad","Puede cambiar el estado de actividad"),
            ("repriorizar", "Puede repriorizar el US"),

        )

    def __unicode__(self):
        return unicode(self.descripcion_corta)


auditlog.register(TipoUS)
auditlog.register(Actividades)
auditlog.register(US)

equipo/models.py
# encoding:utf-8

from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.db import models

from login.models import Usuario
from proyecto.models import Proyecto


# Create your models here.


class Equipo(models.Model):
    """
    Clase Equipo que heredea del modelo Group de django.
    proyecto = proyecto al que pertenece el equipo.
    usuarios = usuarios miembros del equipo.
    """
    nombre = models.CharField(max_length=80)
    permisos = models.ManyToManyField(Permission, blank=True)
    proyecto = models.ForeignKey(Proyecto, null=True, related_name='equipos')
    usuarios = models.ManyToManyField(Usuario, related_name='equipos')

    history = AuditlogHistoryField()

    def __unicode__(self):
        return self.nombre

auditlog.register(Equipo)

proyecto/models.py
#encoding:utf-8
from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.utils import timezone
from django.db import models
from login.models import Usuario
from cliente.models import Cliente

class Proyecto (models.Model):
    """
    Se crea la clase Proyecto, que hereda de Model de django, con los siguientes atributos:
    nombre : El nombre del proyecto.
    fechaCreacion : La fecha en la cual se creo el proyecto.
    fechaInicio : La fecha en la cual se inicia el proyecto.
    fechaFin : La fecha en la cual se termino el proyecto.
    liderProyecto : Usuario lider del proyecto.
    descripcion : breve descripcion del proyecto.
    estado : Estado actual del proyecto, puede ser Pendiente, Anulado, Activo o Finalizado.
    Obvservaciones : Ciertas observaciones del proyecto.
    cliente : Cliente que solicito el proyecto.
    activo : variable que determina un estado de "eliminado" para el Proyecto.


    Metodos:
    hacerLider : Establece un Usuario como lider del proyecto.
    """
    opciones_estado = (
        ('PEN', 'Pendiente'),
        ('ANU', 'Anulado'),
        ('ACT', 'Activo'),
        ('FIN', 'Finalizado'),)
    nombre = models.CharField(max_length=50, null=False)
    fecha_creacion = models.DateField(auto_now=True)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    lider_proyecto = models.ForeignKey(Usuario, related_name='lider')
    descripcion = models.TextField(max_length=140, help_text='Introduzca una breve reseña del proyecto', null=True)
    estado = models.CharField(max_length=3, choices=opciones_estado, default='PEN', help_text='Estado del proyecto')
    observaciones = models.TextField(max_length=140, null=True, default='No hay observaciones')
    cliente = models.ForeignKey(Cliente, on_delete= models.DO_NOTHING)
    activo = models.BooleanField(default=True)

    history = AuditlogHistoryField()

    class Meta:
        permissions = (
            ("view_proyecto", "Puede ver proyecto"),
            ("change_estado", "Puede cambiar el estado del proyecto"),
            ("view_log", "Puede cambiar el estado del proyecto"),
        )

    def hacerLider (self, lider):
        self.lider_proyecto=lider
        self.save()

    def __unicode__ (self):
        return self.nombre

auditlog.register(Proyecto)

sprint/models.py
from __future__ import unicode_literals

from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.db import models

from proyecto.models import Proyecto


# Create your models here.
class Sprint(models.Model):
    """
    Clase Sprint que hereda de models.Model
    nombre = Nombre del Sprint.
    duracion = Duracion calculada del Sprint en dias.
    proyecto = Proyecto al que pertenece el Sprint.
    """

    nombre = models.TextField(default='')
    duracion = models.IntegerField(default=0)
    proyecto = models.ForeignKey(Proyecto, null=True, related_name='sprints')

    options_estado_sprint = (
        ('PEN', 'Pendiente'),
        ('INI', 'Iniciado'),
        ('FIN', 'Finalizado')
    )
    estado_sprint = models.CharField(max_length=3, choices=options_estado_sprint, default='PEN')

    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(null=True)

    history = AuditlogHistoryField()

    class Meta:
        permissions = (
            ("view_sprint", "Puede ver Sprint"),
            ("asignar_us", "Puede asignar US al Sprint"),
            ("iniciar_sprint", "Puede iniciar el Sprint"),
        )

    def __unicode__(self):
        return self.nombre


auditlog.register(Sprint)

proyecto/forms.py
#encoding:utf-8
from django import forms
from login.models import Usuario
from cliente.models import Cliente
from django.utils import timezone

class CambioEstadoForm(forms.Form):
    """
    Form para cambiar estado del proyecto
    """
    opciones_estado = (
        ('PEN', 'Pendiente'),
        ('ANU', 'Anulado'),
        ('ACT', 'Activo'),
        ('FIN', 'Finalizado'),
    )
    nombre = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control','readonly':'true',}))
    fecha_inicio = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control','readonly':'true',}),required=True)
    fecha_fin = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control','readonly':'true',}),required=True)
    lider_proyecto = forms.ModelChoiceField(queryset=Usuario.objects.all(),widget=forms.Select(attrs={'class':'form-control','readonly':'true',}))
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.filter(activo=True),widget=forms.Select(attrs={'class':'form-control','readonly':'true',}))
    descripcion = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','readonly':'true',}), max_length=140, help_text='Introduzca una breve reseña del proyecto')
    estado = forms.ChoiceField(choices=opciones_estado,widget=forms.Select(attrs={'class':'form-control',}), help_text='Estado del proyecto')
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','readonly':'true',}),max_length=140, initial='No hay observaciones.')


class ProyectoForm(forms.Form):
    """
    Form para crear o editar Proyecto
    """

    nombre = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control',}))
    fecha_inicio = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control selector',}),required=True)
    fecha_fin = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control selector',}),required=True)
    lider_proyecto = forms.ModelChoiceField(queryset=Usuario.objects.all(),widget=forms.Select(attrs={'class':'form-control',}))
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.filter(activo=True),widget=forms.Select(attrs={'class':'form-control',}))
    descripcion = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control',}), max_length=140, help_text='Introduzca una breve reseña del proyecto')
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control',}),max_length=140, initial='No hay observaciones.')


    def clean(self):
        """
        Validacion de fecha, inicio menor a fin
        """
        cleaned_data = super(ProyectoForm, self).clean()
        fecha_inicio = cleaned_data.get('fecha_inicio')
        fecha_fin = cleaned_data.get('fecha_fin')
        try:
            if fecha_inicio > fecha_fin:
                msg = "La fecha inicio es mayor a fecha fin"
                self.add_error('fecha_inicio', msg)
                # raise forms.ValidationError("La fecha de inicio es mayor a la de fin")
        except:
            msg = "La fecha inicio es mayor a fecha fin"
            self.add_error('fecha_inicio', msg)


            # return fecha_inicio

proyecto/templates/log_proyecto.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Log Proyecto</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Log Proyecto</h1>
        <h2 class="sub-header">Listado</h2>
        <table class="table table-responsive">
            <thead>
            <tr>
                <th>Actor</th>
                <th>Fecha</th>
                <th>Accion</th>
            </tr>
            </thead>
            <tbody>
            {% for log in log_proyecto %}
                <tr>
                    <td>{{ log.actor }}</td>
                    <td>{{ log.timestamp }}</td>
                    <td>{{ log }}</td>
                </tr>
            {% empty %}
                No existe ningun proyecto.
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

proyecto/templates/proyecto_create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
<title>Proyecto</title>
<link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'jquery-ui-1.11.4/jquery-ui.css' %}">

{% endblock %}

{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Proyectos</h1>
            <h2 class="sub-header">{% if proyecto %}Modificar proyecto {% else %} Crear nuevo proyecto{% endif %}</h2>
            <div class="col-md-offset-3 col-md-6">
                <form action="" method="post">
                    <div class="form-group">
                        <label for="id_nombre">Nombre:</label>
                        {{form.nombre}}
                        <p class="text-danger">{{form.nombre.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_fecha_inicio">Fecha inicio:</label>
                        {{form.fecha_inicio}}
                        <p class="text-danger">{{form.fecha_inicio.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_fecha_fin">Fecha fin:</label>
                        {{form.fecha_fin}}
                        <p class="text-danger">{{form.fecha_fin.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_lider_proyecto">Lider del proyecto:</label>
                        {{form.lider_proyecto}}
                        <p class="text-danger">{{form.lider_proyecto.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_cliente">Cliente:</label>
                        {{form.cliente}}
                        <p class="text-danger">{{form.cliente.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_descripcion">Descripcion:</label>
                        {{form.descripcion}}
                        <p class="text-danger">{{form.descripcion.errors.0}}</p>
                    </div>
                    {% if proyecto and form.estado %}
                    <div class="form-group">
                        <label for="id_estado">Estado:</label>
                        {{form.estado}}
                        <p class="text-danger">{{form.estado.errors.0}}</p>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <label for="id_observaciones">Observaciones:</label>
                        {{form.observaciones}}
                        <p class="text-danger">{{form.observaciones.errors.0}}</p>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Submit" class="form-control primary">
                    </div>
                </form>
            </div>
        </div>

{% endblock %}
{% block scripts %}
  <script src="{% static 'jquery-ui-1.11.4/jquery-ui.js' %}"></script>

  <script>
 $.datepicker.regional['es'] = {
 closeText: 'Cerrar',
 prevText: '<Ant',
 nextText: 'Sig>',
 currentText: 'Hoy',
 monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
 monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
 dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
 dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
 dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
 weekHeader: 'Sm',
 dateFormat: 'dd/mm/yy',
 firstDay: 1,
 isRTL: false,
 showMonthAfterYear: false,
 yearSuffix: ''
 };
 $.datepicker.setDefaults($.datepicker.regional['es']);
  $(function() {
  $( ".selector" ).datepicker({dateFormat: "dd/mm/yy"});
  });
  </script>
{% endblock %}

proyecto/templates/proyecto_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Proyecto</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Proyectos</h1>
        {% if perms.proyecto.add_proyecto %}
            <a class="btn btn-primary" href="/proyecto/create/">Crear nuevo</a>
        {% endif %}
        <a class="btn btn-primary" href="/proyecto/log_proyecto/{{ object.id }}/">Log</a>
        <h2 class="sub-header">Detalle</h2>
        <p>Nombre: <strong>{{ object.nombre }}</strong></p>
        <p>Fecha de inicio: {{ object.fecha_inicio }}</p>
        <p>Fecha de fin: {{ object.fecha_fin }}</p>
        <p>Lider del proyecto: {{ object.lider_proyecto }}</p>
        <p>Cliente: {{ object.cliente }}</p>
        <p>Descripción: {{ object.descripcion }}</p>
        <p>Estado: {{ object.get_estado_display }}</p>
        <p>Observaciones: {{ object.observaciones }}</p>

        {% if perms.proyecto.change_proyecto %}
            <a class="btn btn-default" role="button" href="/proyecto/update/{{ object.id }}">Modificar</a>{% endif %}
        {% if perms.proyecto.delete_proyecto %}
            <a class="btn btn-danger" role="button" href="/proyecto/delete/{{ object.id }}">Eliminar</a>{% endif %}
        {% if perms.proyecto.change_estado %}
            <a class="btn btn-default" role="button" href="/proyecto/cambiar_estado/{{ object.id }}">Cambiar
                estado</a>{% endif %}

        <h2 class="sub-header">Equipos</h2>
        {% if perms.equipo.add_equipo or 'add_equipo' in permisos%}
            {% ifequal bloqueo 'NO' %}
            <a class="btn btn-primary" href="/equipo/create/{{ object.id }}/">Crear nuevo</a>
            {% endifequal %}
        {% endif %}
        <table class="table table-responsive">
            <thead>
            <tr>
                <th>Nombre</th>
                <th>Integrantes</th>
                <th>Permisos</th>
                {% if perms.equipo.delete_equipo or 'delete_equipo' in permisos%}
                    {% ifequal bloqueo 'NO' %}

                        <th></th>
                    {% endifequal %}
                {% endif %}
                {% if perms.equipo.update_equipo or 'update_equipo' in permisos%}
                    {% ifequal bloqueo 'NO' %}

                        <th></th>
                    {% endifequal %}
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for equipo in object.equipos.all %}
                <tr>
                    <td>{{ equipo.nombre }}</td>
                    <td>
                        <ul>{% for u in equipo.usuarios.all %}
                            <li>{{ u }}</li>{% endfor %}</ul>
                    </td>
                    <td>
                        <ul>{% for p in equipo.permisos.all %}
                            <li>{{ p }}</li>{% endfor %}</ul>
                    </td>
                    {% if perms.equipo.delete_equipo or 'delete_equipo' in permisos %}
                        {% ifequal bloqueo 'NO' %}
                            <td><a class="text-danger" href="/equipo/delete/{{ equipo.id }}">borrar</a></td>
                        {% endifequal %}
                    {% endif %}
                    {% if perms.equipo.update_equipo or 'update_equipo' in permisos %}
                        {% ifequal bloqueo 'NO' %}
                            <td><a href="/equipo/update/{{ equipo.id }}">modificar</a></td>
                        {% endifequal %}
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>

        </table>

        <div class="row">
            {% if perms.sprint.view_sprint or 'view_sprint' in permisos %}
            <div class="col-md-6 col-sm-6 col-lg-6">
                <h2 class="sub-header">Sprints</h2>
                {% if perms.sprint.add_sprint or 'add_sprint' in permisos %}
                    {% ifequal bloqueo 'NO' %}
                        {% if object.uss.all %}
                            <a class="btn btn-primary" href="/sprint/create/{{ object.id }}/">Crear nuevo</a>
                        {% else %}
                            <a class="btn btn-primary" href="#"
                               onClick="alert('No puedes crear Sprints sin tener algun us')">Crear
                                nuevo</a>
                        {% endif %}
                    {% endifequal %}
                {% endif %}
                <table class="table table-responsive">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Duración</th>
                        {% if perms.sprint.delete_sprint or 'delete_sprint' in permisos %}
                            {% ifequal bloqueo 'NO' %}
                                <th>Eliminar</th>
                            {% endifequal %}
                        {% endif %}

                    </tr>
                    </thead>
                    <tbody>
                    {% for sprint in object.sprints.all %}
                        <tr>
                            <td><a href="/sprint/{{ sprint.id }}/"> {{ sprint.nombre }}</a></td>
                            <td>{{ sprint.duracion }}</td>
                            {% if sprint.estado_sprint == 'PEN' %}
                                {% if perms.sprint.delete_sprint or 'delete_sprint' in permisos%}
                                    {% ifequal bloqueo 'NO' %}
                                        <td><a class="text-danger" href="/sprint/delete/{{ sprint.id }}">remove</a></td>
                                    {% endifequal %}
                                {% endif %}
                            {% endif %}

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
            <div class="col-md-6 col-sm-6 col-lg-6">
                <h2 class="sub-header">US</h2>
                {% if perms.US.add_us or 'add_us' in permisos %}
                    {% ifequal bloqueo 'NO' %}
                        {% if tipoUS %}
                            <a class="btn btn-primary" href="/us/us/create/{{ object.id }}/">Crear nuevo</a>
                        {% else %}
                            <a class="btn btn-primary" href="#"
                               onClick="alert('No puedes crear US sin tener algun tipo de US')">Crear
                                nuevo</a>
                        {% endif %}
                    {% endifequal %}
                {% endif %}
                <table class="table table-responsive">
                    <thead>
                    <tr>
                        <th>Descripcion Corta</th>
                        <th>Tipo US</th>
                        <th>Actividad</th>
                        <th>Estado</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for us in object.uss.all %}
                        {% if 'view_us' in permisos or perms.us.view_us or us.usuario_asignado == user %}
                        <tr>
                            <td><a href="/us/us/{{ us.id }}/">{{ us.descripcion_corta }}</a></td>
                            <td>{{ us.tipoUS }}</td>
                            {% if us.actividad %}
                                <td>{{ us.actividad }}</td>
                                <td>{{ us.get_estado_actividad_display }}</td>
                            {% else %}
                                <td>Actividad no asignada</td>
                            {% endif %}
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

proyecto/templates/proyecto_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <title>Proyecto</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Proyectos</h1>
            {% if perms.proyecto.add_proyecto %}<a class="btn btn-primary" href="/proyecto/create/">Crear nuevo</a>{% endif %}
            <h2 class="sub-header">Listado</h2>
            <table class="table table-responsive">
                <thead>
                <tr>
                <th>Nombre</th>
                <th>Lider del proyecto</th>
                <th>Cliente</th>
                <th>Estado</th>
                </tr>
                </thead>
                <tbody>
                {% for proyecto in proyecto_list %}
                <tr>
                    <td><a href="/proyecto/{{ proyecto.pk }}">{{ proyecto.nombre }}</a></td>
                    <td>{{proyecto.lider_proyecto}}</td>
                    <td>{{proyecto.cliente}}</td>
                    <td>{{proyecto.get_estado_display}}</td>
                </tr>
                {% empty %}
                No existe ningun proyecto.
                {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock %}